main.cpp:12:5: style: Exception should be caught by reference. [catchExceptionByValue]
  } catch (const std::exception ex) {
    ^
main.cpp:9:33: performance: Function parameter 's' should be passed by const reference. [passedByValue]
std::string f(const std::string s, int i) {
                                ^
